spring.application.name=lubimyczytacpl

# H2
spring.datasource.url=${DB_URL:jdbc:h2:file:./bookdb;AUTO_SERVER=TRUE}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASS:}

# Hibernate
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
